[package]
authors = ["Jonathan Sharman <jonathan.sharman@gmail.com>"]
edition = "2018"
name = "gynjo"
version = "0.1.0"

[dependencies]
bigdecimal = "0.2"
itertools = "0.9"
lazy_static = "1.4"
logos = "0.11"
num = "0.3"
num-traits = "0.2"

[dev-dependencies]
rstest = "0.9"
