[package]
name = "gynjo"
version = "0.1.0"
authors = ["Jonathan Sharman <jonathan.sharman@gmail.com>"]
edition = "2018"

[dependencies]
bigdecimal = "0.1.2"
num-bigint = "0.2.6"
num-traits = "0.2.11"
fancy-regex = "0.3.5"
itertools = "0.9.0"
lazy_static = "1.4.0"
